server:
  port: 8090

spring:
  application:
    name: matt-fullstack
  controller:
    path-prefix: /api
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.orm.jpa: debug
    com.matt.mapper: debug
  path: C:/data/logs
  pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %X{requestId} | %-5level | %logger{36} | %msg%n"
  queue-size: 256

jwt:
  secret: uHJXZyedfN6Vg0kPORXzdAjOYBVclvl_HzabqYRFi7I=
  expirationInSec: 2592000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

auth:
  excludePaths:
    - url: /api/**
      method: OPTIONS
    - url: /api/ping
      method: GET
    - url: /api/auth/login
      method: "*"
    - url: /api/auth/logout
      method: "*"
    - url: /api/users
      method: POST,OPTIONS
    - url: /api/comments
      method: GET
    - url: /api/v3/api-docs
      method: "*"
    - url: /api/v3/api-docs/**
      method: "*"
    - url: /swagger-ui.*
      method: "*"
    - url: /swagger-ui/**
      method: "*"